version: '2.4'

services:
  app:
    image: .dkr.ecr.ap-northeast-1.amazonaws.com/fargate-nginx-flask/app:app-${APP_VERSION}
    build:
      context: ./containers/app
      dockerfile: Dockerfile
    expose:
      - 5000
  nginx:
    image: .dkr.ecr.ap-northeast-1.amazonaws.com/fargate-nginx-flask/app:nginx-${APP_VERSION}
    build:
      context: ./containers/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
