version: "2.4"
services:
  ecs-local-endpoints:
    image: amazon/amazon-ecs-local-container-endpoints
    volumes:
      - /var/run:/var/run
      - $HOME/.aws/:/home/.aws/
    environment:
      ECS_LOCAL_METADATA_PORT: "51679"
      HOME: "/home"
    network_mode: container:local-pause

  app:
    depends_on:
      - ecs-local-endpoints
    network_mode: container:local-pause
    environment:
      ECS_CONTAINER_METADATA_URI: "http://169.254.170.2/v3/containers/app"
      AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: "/creds"

  nginx:
    depends_on:
      - ecs-local-endpoints
    network_mode: container:local-pause
    environment:
      ECS_CONTAINER_METADATA_URI: "http://169.254.170.2/v3/containers/nginx"
      AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: "/creds"
